name: Docker

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
      - release-*
  pull_request:
    branches:
      - main

env:
  REGISTRY: 164288160730.dkr.ecr.us-west-2.amazonaws.com
  IMAGE_NAME: zhksb-api

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Get Login to AWS ECR
        id: ecr-login
        uses: thalesvon/ecr-login@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_REGISTRY_ACCESSID }}
          AWS_DEFAULT_OUTPUT: json
          AWS_REGION: us-west-2
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_REGISTRY_SECRET }}
        with:
          args: 'get-login --no-include-email --region us-west-2'

      - name: Docker Login
        run: ${{ steps.ecr-login.outputs.login-string }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
